---
- name: Clone Virtual Machine(s) from Template
  vmware_guest:
    state: 'poweredoff'
    name: "{{ item }}"
    annotation: "{{ provision_notes }}"
    template: "{{ provision_vmware_template }}"
    datacenter: "{{ provision_vmware_datacenter }}"
    folder: "{{ provision_vmware_datacenter }}/vm/{{ provision_vmware_folder }}"
    cluster: "{{ provision_vmware_cluster | default (omit) }}"
    esxi_hostname: "{{ provision_vmware_esxi_hostname | default (omit) }}"
    hardware:
      num_cpus: "{{ provision_cpus }}"
      memory_mb: "{{ provision_memory * 1024 }}"
      num_cpu_cores_per_socket: 1
      hotadd_cpu: 'yes'
      hotremove_cpu: 'no'
      hotadd_memory: 'yes'
      nested_virt: 'no'
      scsi: 'paravirtual'
    cdrom:
      type: 'none'
  with_items: "{{ provision_resource_names }}"
  delegate_to: localhost
  async: 300
  poll: 0
  register: clone_async

- name: Wait Until Virtual Machine Provisioning Completes
  async_status:
    jid: "{{ item.ansible_job_id }}"
  with_items: "{{ clone_async.results }}"
  until: clone.finished
  retries: 120
  delegate_to: localhost
  register: clone

- debug:
    msg: "{{ clone }}"
...