---
- name: Gather General Facts
  vmware_guest_facts:
    uuid: "{{ item.instance.instance_uuid }}"
    use_instance_uuid: 'yes'
    datacenter: "{{ provision_vmware_datacenter }}"
  with_items: "{{ clone.results }}"
  delegate_to: localhost
  async: 300
  poll: 0
  register: facts_general_async

- name: Wait Until General Facts Are Gathered
  async_status:
    jid: "{{ item.ansible_job_id }}"
  with_items: "{{ facts_general_async.results }}"
  until: facts_general.finished
  retries: 120
  delegate_to: localhost
  register: facts_general

- name: Gather Storage Facts
  vmware_guest_disk_facts:

    uuid: "{{ item.instance.instance_uuid }}"
    use_instance_uuid: 'yes'
    datacenter: "{{ provision_vmware_datacenter }}"
  with_items:
    - "{{ clone.results }}"
  delegate_to: localhost
  async: 300
  poll: 0
  register: facts_storage_async

- name: Wait Until Storage Facts Are Gathered
  async_status:
    jid: "{{ item.ansible_job_id }}"
  with_items: "{{ facts_storage_async.results }}"
  until: facts_storage.finished
  retries: 120
  delegate_to: localhost
  register: facts_storage

- name: Set Stats
  set_stats:
    data:
      provision_results:
        vmware:
          general: "{{ facts_general.results }}"
          storage: "{{ facts_storage.results }}"
...