---
- name: Clone Template
  ansible.builtin.include_tasks: 'clone.yml'

- name: Configure Network
  ansible.builtin.include_tasks: 'network.yml'

- name: Configure Storage
  ansible.builtin.include_tasks: 'disk.yml'

- name: Distribute Metadata
  ansible.builtin.include_tasks: 'attributes.yml'

- name: Power On Resource(s)
  ansible.builtin.include_tasks: 'power.yml'

- name: Return Provisioning Facts
  ansible.builtin.include_tasks: 'facts.yml'
...
