---
- name: Power On Virtual Machine(s)
  community.vmware.vmware_guest:
    uuid: "{{ item.instance.instance_uuid }}"
    use_instance_uuid: 'yes'
    state: 'poweredon'
    wait_for_ip_address: true
  with_items:
    - "{{ clone.results }}"
  delegate_to: localhost
  async: 300
  poll: 0
  register: power_async

- name: Wait For Virtual Machine(s) IP Address(es)
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  with_items: "{{ power_async.results }}"
  until: power.finished
  retries: 120
  delegate_to: localhost
  register: power
...
